# Generated by Django 4.2.1 on 2023-06-02 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('correo', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('hora_creacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id_project', models.AutoField(primary_key=True, serialize=False)),
                ('name_project', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('hora_creacion', models.DateTimeField(auto_now=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD_controler.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Capitulos',
            fields=[
                ('id_capitulo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('numero_del_capitulo', models.CharField(max_length=10)),
                ('lista_etiqueta_capitulo', models.CharField(max_length=100)),
                ('contenido_capitulo', models.TextField(max_length=8000)),
                ('url_capitulo', models.CharField(max_length=400)),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD_controler.proyectos')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD_controler.usuario')),
            ],
        ),
    ]
