# Generated by Django 4.2.1 on 2023-06-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_controler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nickname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
