# Generated by Django 4.2.1 on 2023-06-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_controler', '0004_alter_usuario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nickname',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
