# Generated by Django 4.2.1 on 2023-06-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_controler', '0005_alter_usuario_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='name_project',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
